# Generated by Django 5.0.1 on 2024-03-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_photo_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
