# Generated by Django 5.0.3 on 2024-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
